"""XFA detection and handling.

XFA is a second, XML-based form model that Adobe layered on top of AcroForms.
Three cases matter:

``none``
    No ``/XFA`` entry. Ordinary AcroForm, nothing to do.
``hybrid``
    Static XFA: an ``/XFA`` packet exists *and* there are real AcroForm fields
    with appearance streams. The document renders and fills normally, but
    Acrobat may re-read the XFA ``datasets`` packet when opening the file and
    overwrite whatever was written to the AcroForm side. Dropping the XFA layer
    (:func:`strip_xfa`) leaves a plain AcroForm that behaves predictably.
``dynamic``
    The AcroForm side is an empty stub and the layout is generated by script at
    open time. There is no fixed field list, so there is no schema to derive.

The XFA packet itself is a far richer schema source than the AcroForm - the
``template`` packet carries real names, captions and validation rules - so
:func:`xfa_packets` exposes the raw XML for callers that want to go there.
"""

from __future__ import annotations

from typing import Any

from pypdf.generic import ArrayObject, DictionaryObject, StreamObject

from pdffill.model import XfaKind


def detect_xfa(acroform: DictionaryObject | None) -> XfaKind:
    """Classify the XFA situation of an ``/AcroForm`` dictionary."""
    if acroform is None or "/XFA" not in acroform:
        return XfaKind.NONE
    fields = acroform.get("/Fields")
    n_fields = len(fields.get_object()) if fields is not None else 0
    return XfaKind.HYBRID if n_fields else XfaKind.DYNAMIC


def xfa_packets(acroform: DictionaryObject | None) -> dict[str, bytes]:
    """Return the XFA packets of a form, keyed by packet name.

    ``/XFA`` is either a single stream holding one complete XDP document, or an
    array alternating name and stream (``preamble``, ``config``, ``template``,
    ``datasets``, ``xdp``, ``postamble``). A single stream is returned under the
    key ``xdp``.
    """
    if acroform is None or "/XFA" not in acroform:
        return {}
    raw = acroform["/XFA"].get_object()
    if isinstance(raw, StreamObject):
        return {"xdp": raw.get_data()}
    if not isinstance(raw, (ArrayObject, list)):
        return {}

    packets: dict[str, bytes] = {}
    entries = list(raw)
    for name_obj, stream_obj in zip(entries[::2], entries[1::2], strict=False):
        name = str(name_obj.get_object())
        stream = stream_obj.get_object()
        if not isinstance(stream, StreamObject):
            continue
        packets[name] = stream.get_data()
    return packets


def strip_xfa(catalog: DictionaryObject) -> bool:
    """Remove the XFA layer from a document catalog, in place.

    This is the equivalent of ``pdftk in.pdf output out.pdf drop_xfa``: it leaves
    the AcroForm fields and their appearance streams untouched, so a static XFA
    form becomes an ordinary one. It does nothing useful to a dynamic form,
    whose AcroForm side is empty to begin with.

    Returns:
        Whether an XFA entry was actually present and removed.
    """
    acro: Any = catalog.get("/AcroForm")
    if acro is None:
        return False
    acro = acro.get_object()
    if not isinstance(acro, DictionaryObject) or "/XFA" not in acro:
        return False
    del acro["/XFA"]
    # NeedsRendering marks a document as dynamic XFA; without the XFA packet it
    # would only make viewers complain.
    if "/NeedsRendering" in catalog:
        del catalog["/NeedsRendering"]
    return True
